AliCloud:
  accessKeyId: '******'
  accessKeySecret: '******'
  bucketName: loadimages
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
github:
  client:
    id: '******'
    secret: '******'
  redirect:
    uri: http://localhost:8887/callback
logging:
  file:
    max-history: 30
    max-size: 200MB
    path: logs/log
  level:
    com:
      wenmrong:
        community1:
          community:
            mapper: debug
    root: info

mybatis-plus:
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类路径
  type-aliases-package: com.wenmrong.community1.community.model
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    # 数据库字段驼峰下划线转换
    db-column-underline: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wenmrong.community1.community.mapper
server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(rwlSxdLaKqtRPi34HgMz2g==)
    url: jdbc:mysql://114.132.200.49:3310/community?useSSL=false&serverTimezone=GMT%2B8
    username: root
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: clpvrkzwwvrifafj
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    username: 1985013202@qq.com
  redis:
    database: 0
    host: 114.132.200.49
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    password: ENC(U0MGI+vhGg8q5Lt+X2AGetUPe01QZLZs)
    port: 6379
    timeout: 1800000
rocketmq:
  name-server: 114.132.200.49:9876
  producer:
    group: msg_question_group

#加密
jasypt:
  # 盐加密
  encryptor:
    password: autodidact

