package com.wenmrong.community1.community.model;

import com.baomidou.mybatisplus.annotation.*;
import com.baomidou.mybatisplus.extension.activerecord.Model;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * <p>
 * 
 * </p>
 *
 * @author autodidact
 * @since 2022-09-09
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("notification")
public class Notification extends Model<Notification> {


    @TableId(value = "id", type = IdType.ASSIGN_ID)
    private Long id;

    @TableField("notifier")
    private Long notifier;

    @TableField("receiver")
    private Long receiver;

    @TableField("outerid")
    private Long outerid;

    @TableField("type")
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMT_CREATE
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField(value = "gmt_create", fill = FieldFill.INSERT)
    private Long gmtCreate;


    @TableField("status")
    private Integer status;

    @TableField("notifier_name")
    private String notifierName;

    @TableField("outer_title")
    private String outerTitle;


    @Override
    protected Serializable pkVal() {
        return this.id;
    }

}
