package com.wenmrong.community1.community.model;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import com.baomidou.mybatisplus.extension.handlers.FastjsonTypeHandler;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;
import java.util.List;

import static com.baomidou.mybatisplus.annotation.IdType.ASSIGN_ID;

@Data
@EqualsAndHashCode(callSuper = false)
@TableName(value = "question",autoResultMap = true)
public class Question extends Model<Question> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableId(type = ASSIGN_ID)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TITLE
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("title")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMT_CREATE
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField(value = "gmt_create", fill = FieldFill.INSERT)
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMT_MODIFIED
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField(value = "gmt_modified", fill = FieldFill.INSERT_UPDATE)
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CREATOR
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("creator")
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.COMMENT_COUNT
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("comment_count")
    private Integer commentCount = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VIEW_COUNT
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("view_count")
    private Integer viewCount = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.LIKE_COUNT
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("like_count")
    private Integer likeCount = 0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TAG
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("tag")
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DESCRIPTION
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("description")
    private String description;

    @TableField(value = "label_ids",typeHandler = FastjsonTypeHandler.class)
    private Object labelIds;


}