package com.wenmrong.community1.community.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.extension.activerecord.Model;
import com.wenmrong.community1.community.config.CustomSerializerAndDeserializer;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Objects;

import static com.baomidou.mybatisplus.annotation.IdType.ASSIGN_ID;

@EqualsAndHashCode(callSuper = false)
@TableName("user")
@Data
public class User extends Model<User> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableId(type = ASSIGN_ID)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ACCOUNT_ID
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("account_id")
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NAME
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("name")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.TOKEN
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("token")
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_CREATE
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("gmt_create")
    @JSONField(serializeUsing = CustomSerializerAndDeserializer.class)
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_MODIFIED
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("gmt_modified")
    @JSONField(serializeUsing = CustomSerializerAndDeserializer.class)
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.BIO
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("bio")
    private String bio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.AVATAR_URL
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("avatar_url")
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.EMAIL
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("email")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CODE
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("code")
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.STATUS
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("status")
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("password")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.STAR
     *
     * @mbg.generated Thu May 28 09:25:06 CST 2020
     */
    @TableField("star")
    private String star;



}